version: '2'

services:
  rancher:
    image: rancher/rancher:latest
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/opts/rancher/data/rancher:/var/lib/rancher
      - /home/opts/rancher/data/kubelet:/var/lib/kubelet
      - /home/opts/rancher/data/cni:/var/lib/cni
      - /home/opts/rancher/log:/var/log
    networks:
      - mynet

networks:
    mynet:
      external:
        name: selfnetwork

