version: '2'
services:
    gitlab:
      #image: 'gitlab/gitlab-ce:latest'
      image: 'twang2218/gitlab-ce-zh:latest'
      restart: always
      privileged: true
      user: root
      hostname: 'ip-172-16-10-161'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          #external_url 'http://172.16.10.161:8929/'
          #gitlab_rails['gitlab_shell_ssh_port'] = 2224
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
      ports:
        - '8929:8929'
        - '2224:22'
      volumes:
        - '/home/opts/base-gitlab/config:/etc/gitlab'
        - '/home/opts/base-gitlab/logs:/var/log/gitlab'
        - '/home/opts/base-gitlab/data:/var/opt/gitlab'
      networks:
        - mynet

networks:
    mynet:
      external:
        name: selfnetwork