version: '3'

services:
    opts-data:
      image: alpine
      restart: always
      tty: true
      volumes:
        - opts-data:/opts-data
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
      networks:
        - mynet
networks:
    mynet:
      external:
        name: selfnetwork
volumes:
    opts-data:
      driver_opts:
        type: "nfs"
        o: "addr=172.16.10.153,vers=4,soft,timeo=180,bg,tcp,rw"
        device: ":/home/opts-data"