version: '2'
services:
  tracker:
    image: season/fastdfs:1.2
    container_name: tracker
    restart: always
    volumes:
      - "/home/opts/base-fastdfs/dfs-data/tracker_data:/fastdfs/tracker/data"
    ports: 
      - "22122:22122"
    command: "tracker" 
    network_mode: host
    #networks:
    #  - mynet
 
  storage:
    image: season/fastdfs:1.2
    container_name: storage
    #links: 
    #  - tracker
    restart: always
    volumes:
      - "/home/opts/base-fastdfs/dfs-data/storage.conf:/fdfs_conf/storage.conf"
      #- "/home/opts/base-fastdfs/dfs-data/storage.conf:/etc/fdfs/storage.conf"
      - "/home/opts/base-fastdfs/dfs-data/storage_base_path:/fastdfs/storage/data"
      - "/home/opts/base-fastdfs/dfs-data/store_path0:/fastdfs/store_path"  
    ports: 
      - "23000:23000"
    environment:
      TRACKER_SERVER: "192.168.100.90:22122"
    command: "storage"
    network_mode: host
    #networks:
    #  - mynet
 
  nginx:
    image: season/fastdfs:1.2
    container_name: fdfs-nginx
    restart: always
    volumes:
      - "/home/opts/base-fastdfs/dfs-data/nginx.conf:/etc/nginx/conf/nginx.conf"
      - "/home/opts/base-fastdfs/dfs-data/store_path0:/fastdfs/store_path"
    #links: 
    #  - tracker
    ports: 
      - "8088:8088"
    environment:
      TRACKER_SERVER: "192.168.100.90:22122"
    command: "nginx"
    network_mode: host
    #networks:
    #  - mynet

#networks:
#    mynet:
#      external:
#        name: selfnetwork