version: '3.7'

#glusterfs不能部署
services:
  minio1:
    image: minio/minio
    restart: always
    command: server /data
    volumes:
      - /home/opts/base-minio/data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mynet

networks:
    mynet:
      external:
        name: selfnetwork


