version: '2'
services:
  base-jenkins:
    image: jenkins/jenkins:lts-centos7
    restart: always
    privileged: true
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/opts/base-jenkins/data:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/local/bin/docker
    networks:
      - mynet

networks:
    mynet:
      external:
        name: selfnetwork

