version: '3'
services:
   pptpd:
     image: vimagick/pptpd
     ports:
       - 1723:1723
     volumes:
       - ./data/pptpd.conf:/etc/pptpd.conf
       - ./data/pptpd-options:/etc/ppp/pptpd-options
       - ./data/chap-secrets:/etc/ppp/chap-secrets
     privileged: true
     restart: always
     networks:
       mynet:
         ipv4_address: 172.30.0.8

networks:
    mynet:
      external:
        name: selfnetwork
