version: "2"
services:
  smokeping:
    image: linuxserver/smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/opts/base-smokeping/config:/config
      - /home/opts/base-smokeping/data:/data
    ports:
      - 8082:80
    restart: always
    networks:
      - mynet

networks:
    mynet:
      external:
        name: selfnetwork
